name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    label: breaking
  - title: 🚀 New features and improvements
    label: enhancement
  - title: 🐛 Bug fixes
    label: bug
  - title: 🧰 Maintenance
    label: maintenance
  - title: 📚 Documentation
    label: documentation
  - title: 📦 Dependency updates
    label: dependencies
    collapse-after: 10
  - title: ✍ Other changes


template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

exclude-labels:
  - 'skip-changelog'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  default: patch
