name: Manual Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Image
    uses: ./.github/workflows/build-ecr-artifacts.yml
    with:
      image-tag: ${{ github.sha }}
  # Follow up with a deployment job
