name: PR Checks

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Install dependencies
        run: uv sync --dev
      - name: Run Ruff
        run: uv run ruff check src tests

  test:
    name: Pytest & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Install dependencies
        run: uv sync --dev
      - name: Run Pytest with Coverage
        run: uv run pytest --cov=src --cov-report=xml
      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        if: always()
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
