name: Release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Image ( ${{ github.event.release.tag_name }} release)
    uses: ./.github/workflows/build-ecr-artifacts.yml
    with:
      image-tag: ${{ github.event.release.tag_name }}
  # Follow up with a deployment job
